# Generated by Django 4.1.4 on 2023-09-06 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_icon_alter_user_user_joindate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_teacher',
            new_name='user_is_teacher',
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentGUID', models.CharField(blank=True, max_length=100, null=True)),
                ('communityID', models.CharField(blank=True, max_length=100, null=True)),
                ('communityUID', models.CharField(blank=True, max_length=100, null=True)),
                ('FullName', models.CharField(blank=True, max_length=100, null=True)),
                ('YearLevelCode', models.CharField(blank=True, max_length=10, null=True)),
                ('HouseDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('HomeroomCode', models.CharField(blank=True, max_length=20, null=True)),
                ('HomeroomDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('HomeroomTeachers', models.TextField(blank=True, null=True)),
                ('StudentID', models.CharField(blank=True, max_length=50, null=True)),
                ('StudentPersonalRefId', models.CharField(blank=True, max_length=50, null=True)),
                ('NoteCount', models.IntegerField(blank=True, null=True)),
                ('NoteImportantCount', models.IntegerField(blank=True, null=True)),
                ('ImportantMedicalWarning', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
