# Generated by Django 4.1.4 on 2023-09-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_teacher_user_user_is_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
