# Generated by Django 4.1.4 on 2023-09-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_cookies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_firstName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
