# Generated by Django 4.1.4 on 2023-09-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_user_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to='user_icons/'),
        ),
    ]
