# Generated by Django 4.2.1 on 2023-10-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_user_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_icon',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_userName',
            field=models.CharField(max_length=50),
        ),
    ]
