# Generated by Django 4.2.1 on 2023-10-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_class_alter_userclassesrelationship_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
